import java.util.ArrayList;
import inanimateobjects.*;
import livingthings.abilities.Abilities;
import livingthings.*;

public class Main
{
	public static void main(String[] args) {
		ArrayList<Abilities> abilities = new ArrayList<>();
		KidClothing.PictureOnTheCloth squirrel = new KidClothing.PictureOnTheCloth();
		//squirrel.setPicture("белочка");
		//squirrel.setPictureColor(KidClothing.Colors.RED);
		Shorty secondBaby = new Shorty("Лена", Human.Sex.FEMALE);
		KidClothing redBow = new KidClothing();
		redBow.setColor(KidClothing.Colors.RED);
		redBow.setType(KidClothing.TypeClothing.BOW);
		KidClothing redDress = new KidClothing();
		redDress.setColor(KidClothing.Colors.RED);
		redDress.setType(KidClothing.TypeClothing.DRESS);
		KidClothing orangeShoes = new KidClothing();
		orangeShoes.setColor(KidClothing.Colors.ORANGE);
		orangeShoes.setType(KidClothing.TypeClothing.SHOES);
		KidClothing pinkApron = new KidClothing();
		pinkApron.setColor(KidClothing.Colors.PINK);
		pinkApron.setType(KidClothing.TypeClothing.APRON);
		pinkApron.setPicture(squirrel);
		secondBaby.wearSomething(redBow);
		secondBaby.wearSomething(redDress);
		secondBaby.wearSomething(orangeShoes);
		secondBaby.wearSomething(pinkApron);
		secondBaby.setPlace(Place.HALL);
		Shorty firstBaby = new Shorty("Маша", Human.Sex.FEMALE);
		firstBaby.setPlace(Place.HALL);
		KidClothing.PictureOnTheCloth bunny = new KidClothing.PictureOnTheCloth();
		bunny.setPicture("зайчик");
		bunny.setPictureColor(KidClothing.Colors.GREEN);
		KidClothing orangeBow = new KidClothing();
		orangeBow.setColor(KidClothing.Colors.ORANGE);
		orangeBow.setType(KidClothing.TypeClothing.BOW);
		KidClothing blueTSHIRT = new KidClothing();
		blueTSHIRT.setColor(KidClothing.Colors.BLUE);
		blueTSHIRT.setType(KidClothing.TypeClothing.T_SHIRT);
		KidClothing redSkirt = new KidClothing();
		redSkirt.setColor(KidClothing.Colors.RED);
		redSkirt.setType(KidClothing.TypeClothing.SKIRT);
		KidClothing yellowApron = new KidClothing();
		yellowApron.setColor(KidClothing.Colors.YELLOW);
		yellowApron.setType(KidClothing.TypeClothing.APRON);
		yellowApron.setPicture(bunny);
		firstBaby.wearSomething(orangeBow);
		firstBaby.wearSomething(blueTSHIRT);
		firstBaby.wearSomething(redSkirt);
		firstBaby.wearSomething(orangeShoes);
		firstBaby.wearSomething(yellowApron);
		firstBaby.addAbility(new Abilities("спорить", "c другой малышкой"));
		secondBaby.addAbility(new Abilities("спорить", "c другой малышкой"));
		Shorty neznaika = new Shorty("Незнайка", Human.Sex.MALE);
		KidClothing blueHat = new KidClothing();
		blueHat.setColor(KidClothing.Colors.BLUE);
		blueHat.setType(KidClothing.TypeClothing.HAT);
		KidClothing orangeShirt = new KidClothing();
		orangeShirt.setColor(KidClothing.Colors.ORANGE);
		orangeShirt.setType(KidClothing.TypeClothing.SHIRT);
		KidClothing yellowTrousers = new KidClothing();
		yellowTrousers.setColor(KidClothing.Colors.YELLOW);
		yellowTrousers.setType(KidClothing.TypeClothing.TROUSERS);
		KidClothing greenTie = new KidClothing();
		greenTie.setColor(KidClothing.Colors.GREEN);
		greenTie.setType(KidClothing.TypeClothing.TIE);
		KidClothing orangeBoots = new KidClothing();
		orangeBoots.setColor(KidClothing.Colors.ORANGE);
		orangeBoots.setType(KidClothing.TypeClothing.BOOTS);
		neznaika.wearSomething(blueHat);
		neznaika.wearSomething(orangeShirt);
		neznaika.wearSomething(yellowTrousers);
		neznaika.wearSomething(greenTie);
		neznaika.wearSomething(orangeBoots);
		neznaika.setPlace(Place.BEDROOM);
		neznaika.addAbility(new Abilities("хотеть", "посмотреть кто там спорит"));
		neznaika.addAbility(new Abilities("вскочить с постели"));
		Doors theDoorFromBedToHall = new Doors(Place.BEDROOM, Place.HALL);
		neznaika.addAbility(new Abilities("открыть дверь"));
		theDoorFromBedToHall.open();
		neznaika.changePlace(Place.HALL);
		firstBaby.addAbility(new Abilities("отскочить", "в сторону"));
		secondBaby.addAbility(new Abilities("отскочить", "в сторону"));
		firstBaby.addAbility(new Abilities("схватиться за лоб"));
		secondBaby.addAbility(new Abilities("схватиться за лоб"));
		firstBaby.addAbility(new Abilities("смотреть на Незнайку", "c испугом"));
		secondBaby.addAbility(new Abilities("смотреть на Незнайку", "c испугом"));
		firstBaby.addAbility(new Abilities("заморгать глазами"));
		secondBaby.addAbility(new Abilities("заморгать глазами"));
		firstBaby.addAbility(new Abilities("заплакать"));
		secondBaby.addAbility(new Abilities("заплакать"));
		firstBaby.addAbility(new Abilities("повернуться"));
		secondBaby.addAbility(new Abilities("повернуться"));
		Stairs stairsFromHallToAttic = new Stairs(Place.HALL, Place.ATTIC);
		stairsFromHallToAttic.setHeight(16);
		stairsFromHallToAttic.setWidth(0.4);
		firstBaby.changePlace(Place.STAIRS);
		secondBaby.changePlace(Place.STAIRS);
		firstBaby.addAbility(new Abilities("подниматься"));
		secondBaby.addAbility(new Abilities("подниматься"));
		firstBaby.climbTheStairs(stairsFromHallToAttic);
		secondBaby.climbTheStairs(stairsFromHallToAttic);
	}
}
